version: 0.2

phases:
  install:
    commands:
      - apt install apache2
  build:
    commands:
      - echo "Building"
  post_build:
    commands:
      - echo "Building Done"
artifacts:
  files:
    - appspec.yaml
base-directory: dist
