version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt upgrade -y
      - apt-get  install apache2 -y
  build:
    commands:
      - echo "Building"
  post_build:
    commands:
      - echo "Building Done"
artifacts:
  files:
    - '**/*'
base-directory: dist
